Application/Areas/Admin/Controllers/InstitutionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Helpers.OptionEnums;
using Application.Models;
using Application.Models.NavbarModels;
using Application.Models.ViewModels;
using Application.Net;
using Application.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class InstitutionController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;

        public InstitutionController(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public async Task<IActionResult> Index()
        {
            ClsNavbar clsNavbar = new ClsNavbar(_context);
            InstitutionNavbar institutionNavbar = new InstitutionNavbar();

            var select = await _context.View_NewInstitutes.Where(x => x.flag == true).ToListAsync();

            institutionNavbar.viewNewInstituteses = select;
            institutionNavbar.CommentListNavbar = await clsNavbar.Comment();
            institutionNavbar.ComplaintsListNavbar = await clsNavbar.Complaint();
            institutionNavbar.commentcount = institutionNavbar.CommentListNavbar.Count;
            institutionNavbar.complaintcount = institutionNavbar.ComplaintsListNavbar.Count;

            return View(institutionNavbar);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditInstitution(int id)
        {
            TblINSTITUTE_ViewModel model = new TblINSTITUTE_ViewModel();
            model.Cites = await _context.TblCity_.Select(bg => new SelectListItem
            {
                Text = bg.CityName,
                Value = bg.idCity.ToString()

            }).ToListAsync();


            model.Owners = await _context.TblOwner_.Select(a => new SelectListItem
            {
                Text = a.OwnerName,
                Value = a.idOwner.ToString()
            }).ToListAsync();

            model.Institute_Types = await _context.TblINSTITUTE_TYPE_.Select(a => new SelectListItem
            {
                Text = a.INSTITUTE_TYPE,
                Value = a.idINSTITUTE_TYPE.ToString()
            }).ToListAsync();

            if (id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    TblINSTITUTE_ iNSTITUTE_ = await _context.TblINSTITUTE_.Where(b => b.idInstitues == id).SingleOrDefaultAsync();
                    if (iNSTITUTE_ != null)
                    {
                        model.idInstitues = iNSTITUTE_.idInstitues;
                        model.codeOrgan = iNSTITUTE_.codeOrgan;
                        model.nameOrgan = iNSTITUTE_.nameOrgan;
                        model.nameOrganMain = iNSTITUTE_.nameOrganMain;
                        model.hos = iNSTITUTE_.hos;
                        model.idINSTITUTE_TYPE = iNSTITUTE_.idINSTITUTE_TYPE;
                        model.idowner = iNSTITUTE_.idowner;
                        model.idCity = iNSTITUTE_.idCity;
                        model.ADDRESS = iNSTITUTE_.ADDRESS;
                        model.TEL = iNSTITUTE_.TEL;
                        model.fax = iNSTITUTE_.fax;
                        model.email = iNSTITUTE_.email;
                        model.mobile = iNSTITUTE_.mobile;
                        model.lastUpdate = iNSTITUTE_.lastUpdate;
                        model.flag = iNSTITUTE_.flag;

                    }
                }
            }

            return PartialView("AddEditInstitution", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditInstitution(TblINSTITUTE_ViewModel model, int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                string LastUpdate = "";

                if (id == 0)
                {
                    
                    //insert
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        TblINSTITUTE_ INSTITUTE_model = AutoMapper.Mapper.Map<TblINSTITUTE_ViewModel, TblINSTITUTE_>(model);
                        model.lastUpdate = LastUpdate.GetLastUpdate();
                        model.flag = true;
                        db.TblINSTITUTE_.Add(INSTITUTE_model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type: ToastType.green);

                    return PartialView("_Succefullyresponse", redirecturl);
                }
                else
                {
                    //update
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        TblINSTITUTE_ INSTITUTE_model = AutoMapper.Mapper.Map<TblINSTITUTE_ViewModel, TblINSTITUTE_>(model);
                        model.lastUpdate = LastUpdate.GetLastUpdate();
                        model.flag = true;
                        db.TblINSTITUTE_.Update(INSTITUTE_model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);

                    return PartialView("_Succefullyresponse", redirecturl);
                }
            }

            model.Cites = await _context.TblCity_.Select(bg => new SelectListItem
            {
                Text = bg.CityName,
                Value = bg.idCity.ToString()

            }).ToListAsync();


            model.Owners = await _context.TblOwner_.Select(a => new SelectListItem
            {
                Text = a.OwnerName,
                Value = a.idOwner.ToString()
            }).ToListAsync();

            model.Institute_Types = await _context.TblINSTITUTE_TYPE_.Select(a => new SelectListItem
            {
                Text = a.INSTITUTE_TYPE,
                Value = a.idINSTITUTE_TYPE.ToString()
            }).ToListAsync();

            if (id == 0)
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.addError, type: ToastType.yellow);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
            }

            return PartialView("AddEditInstitution", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteInstitution(int Id)
        {
            
            var Institution = new TblINSTITUTE_();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Institution = await _context.TblINSTITUTE_.Where(i => i.idInstitues == Id).SingleOrDefaultAsync();
                    if (Institution == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("DeleteInstitution", Institution.nameOrgan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteInstitution(int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                string LastUpdate = "";
                TblINSTITUTE_ model = await _context.TblINSTITUTE_.Where(i => i.idInstitues == id).SingleOrDefaultAsync();
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    model.lastUpdate = LastUpdate.GetLastUpdate();
                    model.flag = false;
                    db.TblINSTITUTE_.Update(model);
                    await db.SaveChangesAsync();
                }
                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);
       
                return PartialView("_Succefullyresponse", redirecturl);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.yellow);
 
                return RedirectToAction("Index");
            }
        }
    }
}

Application/Areas/Admin/Views/Institution/AddEditInstitution.cshtml
@model Application.Models.ViewModels.TblINSTITUTE_ViewModel
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application


<form asp-controller="Institution" asp-action="AddEditInstitution" id="addeditnstitution" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditnstitution" data-ajax-mode="replace">


    @*header*@

    @if (Model.idInstitues != 0)
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش" })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن" })
    }

    @*body*@
    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="codeOrgan" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="codeOrgan" class="form-control" />
                    <span asp-validation-for="codeOrgan" class="text-danger"></span>
                </div>
            </div>



            <div class="form-group">
                <label asp-for="nameOrgan" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="nameOrgan" class="form-control" />
                    <span asp-validation-for="nameOrgan" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="nameOrganMain" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="nameOrganMain" class="form-control" />
                    <span asp-validation-for="nameOrganMain" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="hos" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="hos" class="form-control" />
                    <span asp-validation-for="hos" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="ADDRESS" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="ADDRESS" class="form-control" />
                    <span asp-validation-for="ADDRESS" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="TEL" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="TEL" class="form-control" />
                    <span asp-validation-for="TEL" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="fax" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="fax" class="form-control" />
                    <span asp-validation-for="fax" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="email" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="mobile" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="mobile" class="form-control" />
                    <span asp-validation-for="mobile" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="idCity" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="idCity" asp-items="@Model.Cites" class="form-control"></select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="idowner" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="idowner" asp-items="@Model.Owners" class="form-control"></select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="idINSTITUTE_TYPE" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="idINSTITUTE_TYPE" asp-items="@Model.Institute_Types" class="form-control"></select>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="idInstitues" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="idInstitues" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("index","Institution")" />

        </div>


    </div>


    @*footer*@
    @if (Model.idInstitues != 0)
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش" })
    }
    else
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن" })
    }





</form>

Application/Areas/Admin/Views/Institution/DeleteInstitution.cshtml
@model string
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

<form asp-controller="Institution" asp-action="DeleteInstitution">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف اطلاعات" })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","Institution")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف اطلاعات" })

</form>

Application/Areas/Admin/Views/Institution/Index.cshtml
@model Application.Models.NavbarModels.InstitutionNavbar
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

@{
    ViewData["Title"] = "موسسات درمانی";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>لیست موسسات درمانی</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showcategory" data-toggle="modal" asp-action="AddEditInstitution"
                                   data-target="#modal-action-institution">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن موسسه جدید
                                </a>
                            </div>
                        </div>
                    </div>


                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>کد موسسه</th>
                                <th>نام</th>
                                <th>نام ارگان اصلی</th>
                                <th>بیمارستان</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 0;
                                foreach (var item in Model.viewNewInstituteses)
                                {
                                    i++;
                            <tr>
                                <td>@i</td>
                                <td>@item.codeOrgan</td>
                                @if (item.nameOrgan.Length >= 35)
                                {
                                    <td>@item.nameOrgan.Substring(0, 35)...</td>
                                }
                                else
                                {
                                    <td>@item.nameOrgan</td>
                                }
                                @if (item.nameOrganMain.Length >= 35)
                                {
                                    <td>@item.nameOrganMain.Substring(0,35)...</td>
                                }
                                else
                                {
                                    <td>@item.nameOrganMain</td>
                                }
                                <td>@item.hos</td>
                                <td>
                                    <a class="btn btn-info" id="editcategory" data-toggle="modal" asp-action="AddEditInstitution"
                                       data-target="#modal-action-institution" asp-route-Id="@item.idInstitues">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                        ویرایش
                                    </a>

                                    <a class="btn btn-danger" id="showcategory" data-toggle="modal" asp-action="DeleteInstitution"
                                       data-target="#modal-action-institution" asp-route-Id="@item.idInstitues">
                                        <i class="glyphicon glyphicon-trash"></i>
                                        حذف
                                    </a>

                                </td>
                            </tr>
                                }
                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="../Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>


@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-institution", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/institution-index.js"></script>
}