Application/Areas/Admin/Controllers/InformingPrivateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Application.Helpers.OptionEnums;
using Application.Models;
using Application.Models.NavbarModels;
using Application.Models.ViewModels;
using Application.Net;
using Application.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class InformingPrivateController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;
        private readonly IHostingEnvironment _appEnvironmen;
        public InformingPrivateController(ApplicationDbContext context, IServiceProvider serviceProvider, IHostingEnvironment appEnvironmen)
        {
            _context = context;
            _serviceProvider = serviceProvider;
            _appEnvironmen = appEnvironmen;
        }

        public async Task<IActionResult> Index()
        {
            ClsNavbar clsNavbar = new ClsNavbar(_context);
            ViewBag.rootpath = "/upload/thumbnailimage/";
            InformingNavbar informingNavbar = new InformingNavbar();
            List<tbl_Informing> informings = new List<tbl_Informing>();
            var select = await _context.tbl_Informing.Where(x => x.flag == true && x.privatePer == true).ToListAsync();
            foreach (var item in select)
            {
                tbl_Informing _Informing = new tbl_Informing
                {
                    imagename=item.imagename,
                    idInfo = item.idInfo,
                    infoDes = item.infoDes,
                    InfoDateTime = item.InfoDateTime,
                    lastUpdate = item.lastUpdate,
                    privatePer = item.privatePer,
                    flag = item.flag
                };
                informings.Add(_Informing);
            }
            informingNavbar.Informings = select;
            informingNavbar.CommentListNavbar = await clsNavbar.Comment();
            informingNavbar.ComplaintsListNavbar = await clsNavbar.Complaint();
            informingNavbar.commentcount = informingNavbar.CommentListNavbar.Count;
            informingNavbar.complaintcount = informingNavbar.ComplaintsListNavbar.Count;

            return View(informingNavbar);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditInformingPrivate(int Id)
        {
            var Informing = new tbl_Informing();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Informing = await _context.tbl_Informing.Where(i => i.idInfo == Id).SingleOrDefaultAsync();
                    if (Informing == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("AddEditInformingPrivate", Informing);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditInformingPrivate(tbl_Informing model, int id, string redirecturl, IEnumerable<IFormFile> files, string Imgename)
        {
            clsTarikh tarix = new clsTarikh();

            if (ModelState.IsValid)
            {
                var uploud = Path.Combine(_appEnvironmen.WebRootPath, "upload\\normalimage\\");
                foreach (var file in files)
                {
                    if (file != null && file.Length > 0)
                    {
                        var filename = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                        using (var fs = new FileStream(Path.Combine(uploud, filename), FileMode.Create))
                        {
                            await file.CopyToAsync(fs);
                            model.imagename = filename;
                        }

                        InsertShowImage.ImageResizer image = new InsertShowImage.ImageResizer();
                        image.Resize(uploud + filename, _appEnvironmen.WebRootPath + "\\upload\\thumbnailimage\\" + filename);

                    }
                }
                if (id == 0)
                {
                    if (model.imagename == null)
                    {
                        model.imagename = "defaultpic.png";
                    }
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        string lastupdate = "";
                        model.lastUpdate = lastupdate.GetLastUpdate();
                        model.flag = true;
                        model.privatePer = true;
                        model.InfoDateTime = tarix.date() + " " + "|" + " " + tarix.time();
                        db.tbl_Informing.Add(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type: ToastType.green);
                    
                    return PartialView("_Succefullyresponse", redirecturl);
                }
                else
                {
                    if (model.imagename == null)
                    {
                        model.imagename = Imgename;
                    }
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        string lastupdate = "";
                        model.lastUpdate = lastupdate.GetLastUpdate();
                        model.flag = true;
                        model.privatePer = true;
                        model.InfoDateTime = tarix.date() + " " + "|" + " " + tarix.time();
                        db.tbl_Informing.Update(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);
                    
                  return PartialView("_Succefullyresponse", redirecturl);
                }
            }
            else
            {
                if (id == 0)
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.addError, type: ToastType.yellow);
                }
                else
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
                }
                return PartialView("AddEditInformingPrivate", model);
            }
           
        }

        [HttpGet]
        public async Task<IActionResult> DeleteInformingPrivate(int Id)
        {
            var Informing = new tbl_Informing();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Informing = await _context.tbl_Informing.Where(i => i.idInfo == Id).SingleOrDefaultAsync();
                    if (Informing == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("DeleteInformingPrivate", Informing.infoDes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteInformingPrivate(int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                tbl_Informing model = await _context.tbl_Informing.Where(i => i.idInfo == id).SingleOrDefaultAsync();
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    string lastupdate = "";
                    model.lastUpdate = lastupdate.GetLastUpdate();
                    model.flag = false;
                    db.tbl_Informing.Update(model);
                    await db.SaveChangesAsync();
                }
                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);

                return PartialView("_Succefullyresponse", redirecturl);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.yellow);

                return RedirectToAction("Index");
            }
        }
    }
}

Application/Areas/Admin/Views/InformingPrivate/AddEditInformingPrivate.cshtml
@model Application.Models.tbl_Informing
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

<form asp-controller="InformingPrivate" asp-action="AddEditInformingPrivate" method="post" enctype="multipart/form-data">

    @*header*@
    @if (Model.idInfo != 0)
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش اطلاعات" })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن اطلاعات" })
    }

    @*body*@

    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="infoDes" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <textarea asp-for="infoDes" class="form-control" required="required"></textarea>
                    <span asp-validation-for="infoDes" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group">
                <label asp-for="imagename" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    @if (Model.idInfo == 0)
                    {
                        <input type="file" id="files" name="files" required="required" multiple />
                    }
                    else if (Model.idInfo != 0 && Model.imagename != "defaultpic.png")
                    {
                        <input type="file" id="files" name="files" multiple />
                    }
                    else if (Model.idInfo != 0 && Model.imagename == "defaultpic.png")
                    {
                        <input type="file" id="files" name="files" required="required" multiple />
                    }
                    


                </div>
                @if (Model.idInfo != 0)
                {
                    <input type="hidden" name="Imgename" value="@Model.imagename" />
                }
            </div>


            <div class="form-group hidden">
                <label asp-for="idInfo" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="idInfo" class="form-control" />
                </div>
            </div>
            <input type="hidden" name="redirecturl" value="@Url.Action("index","InformingPrivate")" />
        </div>
    </div>

    @*footer*@
    @if (Model.idInfo != 0)
    {
        @*@await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش موسسه" })*@

        <div class="modal-footer">
            <button class="btn btn-info" type="button" data-dismiss="modal" value="برگشت"></button>
            <input type="submit" id="submitdata" class="btn btn-info" value="ویرایش اطلاعیه" />
        </div>
    }
    else
    {
        @*@await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن موسسه" })*@

        <div class="modal-footer">
            <button class="btn btn-info" type="button" data-dismiss="modal" value="برگشت"></button>
            <input type="submit" id="submitdata" class="btn btn-success" value="افزودن اطلاعیه" />
        </div>
    }
</form>
@section Scripts{
    <script>

        $(document).on('Click', '#submitdata', function (evt) {
            evt.preventDefault();
            var data = new FormData();
            //دریافت مقادیر فایل آپلودی
            var fileupload = $("#files").get(0);
            var files = fileupload.files;
            for (var i = 0; i < files.length; i++) {
                data.append('files', files[i]);
            }
            //دریافت مقادیر موجود
            $('input,select').each(function (x,y) {
                data.append($(y).attr('name'), $(y).val());
            });
            $.ajax({
                type: "Post",
                url: '@Url.Action("AddEditInformingPrivate", "InformingPrivate", new { area ="Admin"})',
                contentType: false,
                processData: false,
                data: data
                //وقتی که اطلاعات سمت سرور رفت و جواب از سرور آمد
            }).done(function (res) {
                if (res.status === "success") {
                    alert(res.message);
                    window.location.href = '@Url.Action("Index", "InformingPrivate")';
                }
                else {

                    $.each(res.error, function (a, b) {
                        alert(b);
                    })

                    //alert(res.error);
                }
                //برای وقتی که کلا اطلاعات سمت سرور نرفت و در همان بدو ورود خطا داد
            }).fail(function (xhr, b, error) {
                alert(error);
            })

        });


    </script>
}

Application/Areas/Admin/Views/InformingPrivate/DeleteInformingPrivate.cshtml
@model string
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

<form asp-controller="InformingPrivate" asp-action="DeleteInformingPrivate">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف اطلاعات" })

    <div class="modal-body form-horizontal">
        آیا از حذف  آیتم مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","InformingPrivate")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف اطلاعات" })

</form>

Application/Areas/Admin/Views/InformingPrivate/Index.cshtml
@model Application.Models.NavbarModels.InformingNavbar
@using Application.PublicModel


@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

@{
    ViewData["Title"] = "اطلاعیه های کارکنان";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>لیست اطلاعیه های کارکنان</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">
                                <a class="btn btn-primary marginbutoom" id="showcategory" data-toggle="modal" asp-action="AddEditInformingPrivate"
                                   data-target="#modal-action-informingprivate">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن اطلاعیه جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>متن اطلاعیه</th>
                                <th>تاریخ و ساعت</th>
                                <th>عکس</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 0;
                                foreach (var item in Model.Informings)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        @if (item.infoDes.Length >= 50)
                                        {
                                            <td>@item.infoDes.ToString().Substring(0, 50)...</td>
                                        }
                                        else
                                        {
                                            <td>@item.infoDes.ToString()</td>
                                        }

                                        <td>@item.InfoDateTime</td>

                                        @if (@item.imagename == null)
                                        {
                                            <td>
                                                <p>بدون عکس</p>
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                <img src="@ViewBag.rootpath@item.imagename" style=" width:80px; height:80px" class="thumbnail text-center" />
                                            </td>
                                        }


                                        <td>
                                            <a class="btn btn-info" id="editcategory" data-toggle="modal" asp-action="AddEditInformingPrivate"
                                               data-target="#modal-action-informingprivate" asp-route-Id="@item.idInfo">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showcategory" data-toggle="modal" asp-action="DeleteInformingPrivate"
                                               data-target="#modal-action-informingprivate" asp-route-Id="@item.idInfo">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>


@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-informingprivate", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/informingprivate-index.js"></script>
    <script>

        $(document).on('Click', '#submitdata', function (evt) {
            evt.preventDefault();
            var data = new FormData();
            //دریافت مقادیر فایل آپلودی
            var fileupload = $("#files").get(0);
            var files = fileupload.files;
            for (var i = 0; i < files.length; i++) {
                data.append('files', files[i]);
            }
            //دریافت مقادیر موجود
            $('input,select').each(function (x,y) {
                data.append($(y).attr('name'), $(y).val());
            });
            $.ajax({
                type: "Post",
                url: '@Url.Action("AddEditInformingPrivate", "InformingPrivate", new { area ="Admin"})',
                contentType: false,
                processData: false,
                data: data
                //وقتی که اطلاعات سمت سرور رفت و جواب از سرور آمد
            }).done(function (res) {
                if (res.status === "success") {
                    alert(res.message);
                    window.location.href = '@Url.Action("Index", "InformingPrivate")';
                }
                else {

                    $.each(res.error, function (a, b) {
                        alert(b);
                    })

                    //alert(res.error);
                }
                //برای وقتی که کلا اطلاعات سمت سرور نرفت و در همان بدو ورود خطا داد
            }).fail(function (xhr, b, error) {
                alert(error);
            })

        });


    </script>
}