Application/Areas/Admin/Controllers/ServiceTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Helpers.OptionEnums;
using Application.Models;
using Application.Models.NavbarModels;
using Application.Models.ViewModels;
using Application.Net;
using Application.Net.OptionEnums;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.OData.Query.SemanticAst;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceTableController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;

        public ServiceTableController(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public async Task<IActionResult> Index()
        {
            ClsNavbar clsNavbar = new ClsNavbar(_context);
            ServiceTableNavbar servicetablenavbar = new ServiceTableNavbar();

            var select = await _context.ServiceTables.Include(s => s.TblCity).Include(s => s.TblEducation)
                .ToListAsync();

            servicetablenavbar.ServiceTables = select;
            servicetablenavbar.CommentListNavbar = await clsNavbar.Comment();
            servicetablenavbar.ComplaintsListNavbar = await clsNavbar.Complaint();
            servicetablenavbar.commentcount = servicetablenavbar.CommentListNavbar.Count;
            servicetablenavbar.complaintcount = servicetablenavbar.ComplaintsListNavbar.Count;

            return View(servicetablenavbar);
        }

        [HttpGet]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddEdit(int id)
        {
            var model = await _context.ServiceTables.FirstOrDefaultAsync(c => c.Id == id);

            ViewBag.City = new SelectList(await _context.TblCity_.ToListAsync(), "idCity", "CityName");

            ViewBag.Edu = new SelectList(await _context.tbl_Education.ToListAsync(), "idEdu", "EduName");

            if (model != null)
            {
                return PartialView("AddEdit", model);
            }

            return PartialView("AddEdit", new ServiceTable());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit(string id, ServiceTable model, string redirectUrl)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrWhiteSpace(id))
                {
                    await _context.ServiceTables.AddAsync(model);
                    await _context.SaveChangesAsync();

                    TempData["Notification"] = Notification.ShowNotif(MessageType.Add, ToastType.green);
                    return PartialView("_Succefullyresponse", redirectUrl);
                }

                _context.ServiceTables.Update(model);
                await _context.SaveChangesAsync();

                TempData["Notification"] = Notification.ShowNotif(MessageType.Edit, ToastType.blue);
                return PartialView("_Succefullyresponse", redirectUrl);
            }

            return PartialView("AddEdit", model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var servicetable = new ServiceTable();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    servicetable = await _context.ServiceTables.FirstOrDefaultAsync(s => s.Id == Id);
                    if (servicetable == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {

                var model = await _context.ServiceTables.FirstOrDefaultAsync(s => s.Id == id);
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    db.ServiceTables.Update(model);
                    await db.SaveChangesAsync();
                }

                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);

                return PartialView("_Succefullyresponse", redirecturl);

            }

            TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.yellow);

            return RedirectToAction("Index");





        }

        public IActionResult exportExcel()
        {

            byte[] filecontents;

            using (var pakage = new ExcelPackage())
            {
                var worksheet = pakage.Workbook.Worksheets.Add("Sheet1");


                worksheet.Cells[1, 1].Value = "کد";
                worksheet.Cells[1, 1].Style.Font.Size = 12;
                worksheet.Cells[1, 1].Style.Font.Bold = true;
                worksheet.Cells[1, 1].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 2].Value = "جنسیت";
                worksheet.Cells[1, 2].Style.Font.Size = 12;
                worksheet.Cells[1, 2].Style.Font.Bold = true;
                worksheet.Cells[1, 2].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 3].Value = "شهرستان";
                worksheet.Cells[1, 3].Style.Font.Size = 12;
                worksheet.Cells[1, 3].Style.Font.Bold = true;
                worksheet.Cells[1, 3].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 4].Value = "سن";
                worksheet.Cells[1, 4].Style.Font.Size = 12;
                worksheet.Cells[1, 4].Style.Font.Bold = true;
                worksheet.Cells[1, 4].Style.Border.Top.Style = ExcelBorderStyle.Hair;


                worksheet.Cells[1, 5].Value = "تحصیلات";
                worksheet.Cells[1, 5].Style.Font.Size = 12;
                worksheet.Cells[1, 5].Style.Font.Bold = true;
                worksheet.Cells[1, 5].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 6].Value = "شغل";
                worksheet.Cells[1, 6].Style.Font.Size = 12;
                worksheet.Cells[1, 6].Style.Font.Bold = true;
                worksheet.Cells[1, 6].Style.Border.Top.Style = ExcelBorderStyle.Hair;


                worksheet.Cells[1, 7].Value = "برای دریافت چه خدمتی مراجعه نموده اید؟";
                worksheet.Cells[1, 7].Style.Font.Size = 12;
                worksheet.Cells[1, 7].Style.Font.Bold = true;
                worksheet.Cells[1, 7].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 8].Value = "دفعات مراجعه برای دریافت خدمت در سال اخیر:";
                worksheet.Cells[1, 8].Style.Font.Size = 12;
                worksheet.Cells[1, 8].Style.Font.Bold = true;
                worksheet.Cells[1, 8].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 9].Value = "سوال اول";
                worksheet.Cells[1, 9].Style.Font.Size = 12;
                worksheet.Cells[1, 9].Style.Font.Bold = true;
                worksheet.Cells[1, 9].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 10].Value = "سوال دوم";
                worksheet.Cells[1, 10].Style.Font.Size = 12;
                worksheet.Cells[1, 10].Style.Font.Bold = true;
                worksheet.Cells[1, 10].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 11].Value = "سوال سوم";
                worksheet.Cells[1, 11].Style.Font.Size = 12;
                worksheet.Cells[1, 11].Style.Font.Bold = true;
                worksheet.Cells[1, 11].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 12].Value = "سوال چهارم";
                worksheet.Cells[1, 12].Style.Font.Size = 12;
                worksheet.Cells[1, 12].Style.Font.Bold = true;
                worksheet.Cells[1, 12].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 13].Value = "سوال پنجم";
                worksheet.Cells[1, 13].Style.Font.Size = 12;
                worksheet.Cells[1, 13].Style.Font.Bold = true;
                worksheet.Cells[1, 13].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 14].Value = "سوال ششم";
                worksheet.Cells[1, 14].Style.Font.Size = 12;
                worksheet.Cells[1, 14].Style.Font.Bold = true;
                worksheet.Cells[1, 14].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 15].Value = "سوال هفتم";
                worksheet.Cells[1, 15].Style.Font.Size = 12;
                worksheet.Cells[1, 15].Style.Font.Bold = true;
                worksheet.Cells[1, 15].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 16].Value = "سوال هشتم";
                worksheet.Cells[1, 16].Style.Font.Size = 12;
                worksheet.Cells[1, 16].Style.Font.Bold = true;
                worksheet.Cells[1, 16].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 17].Value = "سوال نهم";
                worksheet.Cells[1, 17].Style.Font.Size = 12;
                worksheet.Cells[1, 17].Style.Font.Bold = true;
                worksheet.Cells[1, 17].Style.Border.Top.Style = ExcelBorderStyle.Hair;

                worksheet.Cells[1, 18].Value = "سوال دهم";
                worksheet.Cells[1, 18].Style.Font.Size = 12;
                worksheet.Cells[1, 18].Style.Font.Bold = true;

Application/Areas/Admin/Views/ServiceTable/AddEdit.cshtml
@model Application.Models.ServiceTable
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application


<form asp-controller="ServiceTable" asp-action="AddEdit" id="addeditservicetable" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditservicetable" data-ajax-mode="replace">


    @*header*@

    @if (Model.Id != 0)
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش " })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن " })
    }





    @*body*@

    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="Gender" class="col-lg-3 col-sm-3 control-label">مرد</label>
                <div class="col-lg-6">
                    <input asp-for="Gender" value="1" class="form-control" />
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <label asp-for="Gender" class="col-lg-3 col-sm-3 control-label">زن</label>
                <div class="col-lg-6">
                    <input asp-for="Gender" value="0" class="form-control" />
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group">
                <label asp-for="IdCity" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="IdCity" asp-items="@ViewBag.City" class="form-control"></select>
                </div>
            </div>
            
            <div class="form-group">
                <label asp-for="Age" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="IdEdu" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="IdEdu" asp-items="@ViewBag.Edu" class="form-control"></select>
                </div>
            </div>



            <div class="form-group">
                <label asp-for="Job" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Job" class="form-control" />
                    <span asp-validation-for="Job" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="WicheService" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="WicheService" class="form-control" />
                    <span asp-validation-for="WicheService" class="text-danger"></span>
                </div>
            </div>
            
            <div class="form-group">
                <label asp-for="FlagMoraje" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="FlagMoraje" class="form-control" />
                    <span asp-validation-for="FlagMoraje" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Des" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <textarea asp-for="Des" class="form-control"></textarea>
                    <span asp-validation-for="Des" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("index","servicetable")" />

        </div>


    </div>


    @*footer*@
    @if (Model.Id != 0)
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش " })
    }
    else
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن " })
    }





</form>

Application/Areas/Admin/Views/ServiceTable/Delete.cshtml
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

<form asp-controller="ServiceTable" asp-action="Delete">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف " })

    <div class="modal-body form-horizontal">
        آیا از حذف  آیتم مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","ServiceTable")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف " })

</form>

Application/Areas/Admin/Views/ServiceTable/Index.cshtml
@model Application.Models.NavbarModels.ServiceTableNavbar
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

@{
    ViewBag.Title = "میز خدمت";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>میز خدمت</strong>
                </div>
                <div style="margin-bottom: 0;">
                    <form method="post" asp-controller="ServiceTable" asp-action="exportExcel">

                        <div class="input-group" style="margin-top: 7px;">

                            @*<div class="input-group col-md-2 pull-right">
                                <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#todate1">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </div>
                                <input type="text" class="form-control" id="todate1" name="todate1" placeholder="تا تاریخ" data-MdDateTimePicker="true" data-placement="right" />
                            </div>*@

                            @*<div class="input-group col-md-2 pull-right" style="margin-left: 7px;">
                                <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </div>
                                <input type="text" class="form-control" id="fromDate1" name="fromDate1" placeholder="از تاریخ" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="right" />
                            </div>*@



                            <div class="input-group-btn">
                               @* <button style="border-radius: 4px; margin-right: 20px; margin-left: 50px;" class="btn btn-primary" type="submit">جستجو</button>*@

                                @*<button style="border-radius: 4px; margin-top: 2px;  margin-right: 20px; margin-left: 50px;" class="btn btn-primary" onclick="exportTableToExcel('example',prompt('نام فایل را وارد کنید:'))">خروجی اکسل</button>*@
                                <button style="border-radius: 4px; margin-top: 2px;  margin-right: 20px; margin-left: 50px;" class="btn btn-primary" asp-action="exportExcel" asp-controller="ServiceTable">خروجی اکسل</button>

                            </div>
                        </div>
                    </form>




                </div>
                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">

                                <a class="btn btn-primary marginbutoom" id="showcategory" data-toggle="modal" asp-action="AddEdit"
                                   data-target="#modal-action-surveyofiinsured">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن اداره جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>جنسیت</th>
                                <th>شهر</th>
                                <th>سن</th>
                                <th>تحصیلات</th>
                                <th>شغل</th>
                                <th>برای دریافت چه خدمتی مراجعه نموده اید؟</th>
                                <th>دفعات مراجعه برای دریافت خدمت در سال اخیر:</th>
                                @*<th>سوال 1</th>
                        <th>سوال 2</th>
                        <th>سوال 3</th>
                        <th>سوال 4</th>
                        <th>سوال 5</th>
                        <th>سوال 6</th>
                        <th>سوال 7</th>
                        <th>سوال 8</th>
                        <th>سوال 9</th>
                        <th>سوال 10</th>
                        <th>سوال 11</th>
                        <th>سوال 12</th>
                        <th>سوال 13</th>
                        <th>سوال 14</th>
                        <th>سوال 15</th>
                        <th>سوال 16</th>*@
                                <th>توضیحات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 0;
                                foreach (var item in Model.ServiceTables)
                                {
                                    i++;
                                    <tr>
                                        <td>@i</td>
                                        @if (item.Gender)
                                        {
                                            <td>مرد</td>
                                        }
                                        else
                                        {
                                            <td>زن</td>
                                        }

                                        <td>@item.TblCity?.CityName</td>
                                        <td>@item.Age</td>
                                        <td>@item.TblEducation?.EduName</td>
                                        <td>@item.Job</td>
                                        <td>@item.WicheService</td>
                                        <td>@item.FlagMoraje</td>
                                        <td>@item.Des</td>


                                        <td>
                                            <a class="btn btn-info" id="editcategory" data-toggle="modal" asp-action="AddEdit"
                                               data-target="#modal-action-surveyofiinsured" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                                ویرایش
                                            </a>

                                            <a class="btn btn-danger" id="showcategory" data-toggle="modal" asp-action="Delete"
                                               data-target="#modal-action-surveyofiinsured" asp-route-Id="@item.Id">
                                                <i class="glyphicon glyphicon-trash"></i>
                                                حذف
                                            </a>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-surveyofiinsured", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/ServiceTable.js"></script>
}