Application/Areas/Admin/Controllers/EdaratController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Helpers.OptionEnums;
using Application.Models;
using Application.Models.NavbarModels;
using Application.Models.ViewModels;
using Application.Net;
using Application.Net.OptionEnums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Application.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class EdaratController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;

        public EdaratController(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        public async Task<IActionResult> Index()
        {
            ClsNavbar clsNavbar = new ClsNavbar(_context);
            EdaratNavbar edaratNavbar = new EdaratNavbar();

            var select = await _context.Tbl_Edarat.Where(x => x.flag == true).ToListAsync();

            edaratNavbar.tblEdarats = select;
            edaratNavbar.CommentListNavbar = await clsNavbar.Comment();
            edaratNavbar.ComplaintsListNavbar = await clsNavbar.Complaint();
            edaratNavbar.commentcount = edaratNavbar.CommentListNavbar.Count;
            edaratNavbar.complaintcount = edaratNavbar.ComplaintsListNavbar.Count;

            return View(edaratNavbar);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditEdarat(int Id)
        {
            var Edarat = new Tbl_Edarat();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Edarat = await _context.Tbl_Edarat.Where(i => i.idOffice == Id).SingleOrDefaultAsync();
                    if (Edarat == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("AddEditEdarat", Edarat);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditEdarat(Tbl_Edarat model, int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        string lastupdate = "";
                        model.lastUpdate = lastupdate.GetLastUpdate();
                        model.flag = true;
                        db.Tbl_Edarat.Add(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Add, type: ToastType.green);
                   
                    return PartialView("_Succefullyresponse", redirecturl);
                }
                else
                {
                    using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        string lastupdate = "";
                        model.lastUpdate = lastupdate.GetLastUpdate();
                        model.flag = true;
                        db.Tbl_Edarat.Update(model);
                        await db.SaveChangesAsync();
                    }
                    TempData["Notif"] = Notification.ShowNotif(MessageType.Edit, type: ToastType.blue);
                   
                    return PartialView("_Succefullyresponse", redirecturl);
                }
            }
            else
            {
                if (id == 0)
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.addError, type: ToastType.yellow);
                }
                else
                {
                    TempData["Notif"] = Notification.ShowNotif(MessageType.editError, type: ToastType.yellow);
                }
                return PartialView("AddEditEdarat", model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DeleteEdarat(int Id)
        {
            var Edarat = new Tbl_Edarat();
            if (Id != 0)
            {
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Edarat = await _context.Tbl_Edarat.Where(i => i.idOffice == Id).SingleOrDefaultAsync();
                    if (Edarat == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return PartialView("DeleteEdarat", Edarat.admin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteEdarat(int id, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                Tbl_Edarat model = await _context.Tbl_Edarat.Where(i => i.idOffice == id).SingleOrDefaultAsync();
                using (var db = _serviceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    string lastupdate = "";
                    model.lastUpdate = lastupdate.GetLastUpdate();
                    model.flag = false;
                    db.Tbl_Edarat.Update(model);
                    await db.SaveChangesAsync();
                }
                TempData["Notif"] = Notification.ShowNotif(MessageType.Delete, type: ToastType.red);
               
                return PartialView("_Succefullyresponse", redirecturl);
            }
            else
            {
                TempData["Notif"] = Notification.ShowNotif(MessageType.deleteError, type: ToastType.yellow);
                
                return RedirectToAction("Index");
            }




        }
    }
}

Application/Areas/Admin/Views/Edarat/AddEditEdarat.cshtml
@model Application.Models.Tbl_Edarat
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application


<form asp-controller="Edarat" asp-action="AddEditEdarat" id="addeditedarat" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#addeditedarat" data-ajax-mode="replace">


    @*header*@

    @if (Model.idOffice != 0)
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش اداره" })
    }
    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن اداره" })
    }





    @*body*@

    <div class="modal-body form-horizontal">

        <div class="row">
            <div class="form-group">
                <label asp-for="city" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="city" class="form-control" />                   
                    <span asp-validation-for="city" class="text-danger"></span>
                </div>
            </div>



            <div class="form-group">
                <label asp-for="admin" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="admin" class="form-control" />
                    <span asp-validation-for="admin" class="text-danger"></span>
                </div>
            </div>



            <div class="form-group">
                <label asp-for="Tell" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Tell" class="form-control" />
                    <span asp-validation-for="Tell" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Fax" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Fax" class="form-control" />
                    <span asp-validation-for="Fax" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="adress" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <textarea asp-for="adress" class="form-control" ></textarea>
                    <span asp-validation-for="adress" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="x" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="x" class="form-control" />
                    <span asp-validation-for="x" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="y" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="y" class="form-control" />
                    <span asp-validation-for="y" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="idOffice" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="idOffice" class="form-control" />
                </div>
            </div>

            <input type="hidden" name="redirecturl" value="@Url.Action("index","Edarat")" />

        </div>


    </div>


    @*----------------------------------------------------------------------------------------------------------------------*@

    @*<div class="modal-dialog">
            <div class="modal-content bg-success">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="text-center">
                        <span class="icon icon-check icon-5x"></span>
                        <h3>Success</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                            <br>Animi ducimus id itaque totam saepe reiciendis corporis consectetur.
                        </p>
                        <div class="m-t-lg">
                            <button class="btn btn-default" data-dismiss="modal" type="button">Continue</button>
                            <button class="btn btn-success" data-dismiss="modal" type="button">Cancel</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>*@

    @*--------------------------------------------------------------------------------------------------------------------------------*@

    @*<div role="dialog">
            <div class="modal-dialog">
                <div class="modal-content animated bounceIn">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                            <span class="sr-only">Close</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <span class="text-success icon icon-check icon-5x"></span>
                            <h3 class="text-success">Success</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                <br>Animi ducimus id itaque totam saepe reiciendis corporis consectetur.
                            </p>
                            <div class="m-t-lg">
                                <button class="btn btn-success" data-dismiss="modal" type="button">Continue</button>
                                <button class="btn btn-default" data-dismiss="modal" type="button">Cancel</button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer"></div>
                </div>
            </div>
        </div>*@



    @*footer*@
    @if (Model.idOffice != 0)
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "ویرایش اداره" })
    }
    else
    {
        @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن اداره" })
    }





</form>

Application/Areas/Admin/Views/Edarat/DeleteEdarat.cshtml
@model string
@using Application.PublicModel

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

<form asp-controller="Edarat" asp-action="DeleteEdarat">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف اداره" })

    <div class="modal-body form-horizontal">
        آیا از حذف  @Model مطمئن هستید؟
    </div>

    <input type="hidden" name="redirecturl" value="@Url.Action("index","Edarat")" />


    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف اداره" })

</form>

Application/Areas/Admin/Views/Edarat/Index.cshtml
@model Application.Models.NavbarModels.EdaratNavbar
@using Application.PublicModel


@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Application

@{
    ViewBag.Title = "ادارات شهرستانی";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="color:white;text-align:center" class=@TempData["css"]>
    @if (TempData["notice"] != null)
    {
        <p>@TempData["notice"]</p>
    }
</div>
<div class="layout-content-body">
    <div class="row gutter-xs">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-actions">
                        <button type="button" class="card-action card-toggler" title="Collapse"></button>
                        <button type="button" class="card-action card-reload" title="Reload"></button>
                        <button type="button" class="card-action card-remove" title="Remove"></button>
                    </div>
                    <strong>لیست ادارات شهرستانی</strong>
                </div>

                <div class="card-body">

                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="md-form-group md-label-floating col-md-6">
                            <input class="md-form-control" type="text" name="name" id="serachInput" spellcheck="false" required="" aria-required="true">
                            <label class="md-control-label">جستجو</label>
                        </div>
                    </div>
                    <div class="md-form-group md-label-floating col-md-6">
                        <div class="margin-top">
                            <div class="col-xs-6 col-md-6">

                                <a class="btn btn-primary marginbutoom" id="showcategory" data-toggle="modal" asp-action="AddEditEdarat"
                                   data-target="#modal-action-edarat">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    افزودن اداره جدید
                                </a>
                            </div>
                        </div>
                    </div>
                    <table id="example" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>کد</th>
                                <th>شهرستان</th>
                                <th>رئیس اداره</th>
                                <th>تلفن</th>
                                <th>آدرس</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 0;
                                foreach (var item in Model.tblEdarats)
                                {
                                    i++;
                            <tr>
                                <td>@i</td>
                                <td>@item.city.ToString()</td>
                                <td>@item.admin</td>
                                <td>@item.Tell</td>
                                @if (item.adress.Length >= 50)
                                {
                                    <td>@item.adress.Substring(0, 50)</td>
                                }
                                else
                                {
                                    <td>@item.adress</td>
                                }

                                <td>
                                    <a class="btn btn-info" id="editcategory" data-toggle="modal" asp-action="AddEditEdarat"
                                       data-target="#modal-action-edarat" asp-route-Id="@item.idOffice">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                        ویرایش
                                    </a>

                                    <a class="btn btn-danger" id="showcategory" data-toggle="modal" asp-action="DeleteEdarat"
                                       data-target="#modal-action-edarat" asp-route-Id="@item.idOffice">
                                        <i class="glyphicon glyphicon-trash"></i>
                                        حذف
                                    </a>

                                </td>
                            </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="progress" class="addModal">
    <div class="addCenter">
        <img src="~/Content/loading.gif" />
    </div>
</div>
<div id="infoModalAlertColored" tabindex="-1" role="dialog" class="modal fade">

</div>
<div id="successModalAlert" tabindex="-1" role="dialog" class="modal fade">

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-edarat", Size = ModalSize.Medium })

@section Scripts{
    <script src="~/js/modal-js/edarat-index.js"></script>
}